apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: cloudwatch-agent

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: {{ .Values.namespace }}